spring:
  application:
    name: firstjobapp

# H2 Database

#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test

# PostgreSQL Database
  datasource:
    url: jdbc:postgresql://localhost:5432/jobapp
    username: parjunb
    password: parjunb


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate  #update #create-drop
    database: POSTGRESQL
    #database-platform: org.hibernate.dialect.PostgreSQLDialect

#actuator related
management:
  endpoints:
    web:
      exposure:
        #include: "*"
        include:
          - info
          - loggers
          - metrics
          - shutdown

  endpoint:
    health:
      show-details: ALWAYS
    #enabling shutdown end point
    shutdown:
      enabled: false #true

  info:
    env:
      enabled: true

#setting application information in info end point
info:
  app:
    name: "JobApplication"
    description: "Backend Service for JobApplication. Build by ARJUN B."
    version: "1.0.0"


server:
  shutdown: GRACEFUL